### ISSUE TITLE
Look into server side and ensure persistent connections are reported

### ISSUE THREAD

**Issue by kentfredric** [wbraswell/cloudforfree.org#7]
Analysis by : http://www.webpagetest.org/result/161227_0K_ZNE/1/performance_optimization/ 

Indicated that persistent connections weren't supported for many requests, which leads
to additional TCP/IP overhead ( and latency ) in renegotiating the transfer.

This is something that requires looking into the serving technology and making sure the right features are configured. ( It really should be default, but apparently it might not be )

**Comment by wbraswell** [comment]
I have upgraded the custom components of the CloudForFree.org software in order to support multi-threaded (forked) server mode, which thankfully seems to have solved this and likely other issues!
https://www.webpagetest.org/result/170103_AP_A1P/
